/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollaborationInviteTokenRouteImport } from './routes/collaboration.invite.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationInviteTokenRoute =
  CollaborationInviteTokenRouteImport.update({
    id: '/collaboration/invite/$token',
    path: '/collaboration/invite/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collaboration/invite/$token': typeof CollaborationInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collaboration/invite/$token': typeof CollaborationInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collaboration/invite/$token': typeof CollaborationInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collaboration/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collaboration/invite/$token'
  id: '__root__' | '/' | '/collaboration/invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollaborationInviteTokenRoute: typeof CollaborationInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaboration/invite/$token': {
      id: '/collaboration/invite/$token'
      path: '/collaboration/invite/$token'
      fullPath: '/collaboration/invite/$token'
      preLoaderRoute: typeof CollaborationInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollaborationInviteTokenRoute: CollaborationInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
