import type { HelpArticle } from '../help-types'

import chatArtifactsContent from './articles/chat/chat-artifacts.md?raw'
import chatAttachmentsContent from './articles/chat/chat-attachments.md?raw'
import chatCompactionContent from './articles/chat/chat-compaction.md?raw'
import chatFeedbackContent from './articles/chat/chat-feedback.md?raw'
import chatFilesContent from './articles/chat/chat-files.md?raw'
import chatForkSessionContent from './articles/chat/chat-fork-session.md?raw'
import chatOverviewContent from './articles/chat/chat-overview.md?raw'
import chatProfilesContent from './articles/chat/chat-profiles.md?raw'
import chatProjectAgentsContent from './articles/chat/chat-project-agents.md?raw'
import chatSendingContent from './articles/chat/chat-sending.md?raw'
import chatSessionsContent from './articles/chat/chat-sessions.md?raw'
import chatSidebarContent from './articles/chat/chat-sidebar.md?raw'
import chatSourceControlContent from './articles/chat/chat-source-control.md?raw'
import chatSystemPromptContent from './articles/chat/chat-system-prompt.md?raw'
import chatWorkersContent from './articles/chat/chat-workers.md?raw'

export const chatArticles: HelpArticle[] = [
  {
    id: 'chat-overview',
    title: 'Chat Interface',
    category: 'chat',
    summary: 'How the chat interface works, including streaming responses, workspace rail surfaces, and stopping agents.',
    content: chatOverviewContent,
    keywords: [
      'chat',
      'streaming',
      'stop',
      'status',
      'channel',
      'context window',
      'overview',
      'active work',
      'work plan',
      'source control',
      'worktree',
      'git',
      'files',
      'edit',
      'CodeMirror',
      'reply',
      'quote',
      'quoted preview',
      'reply target',
    ],
    relatedIds: ['chat-sending', 'chat-sidebar', 'chat-compaction', 'chat-files', 'chat-source-control'],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-sending',
    title: 'Sending Messages',
    category: 'chat',
    summary: 'How to send messages, keyboard shortcuts, formatting mode, and slash commands.',
    content: chatSendingContent,
    keywords: [
      'send',
      'enter',
      'format',
      'slash',
      'command',
      'draft',
      'voice',
      'microphone',
      'keyboard',
      'reply',
      'quote',
      'quoted preview',
      'reply target',
    ],
    relatedIds: ['chat-overview', 'chat-attachments'],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-attachments',
    title: 'Attachments',
    category: 'chat',
    summary: 'How to attach files and images to messages.',
    content: chatAttachmentsContent,
    keywords: [
      'attach',
      'file',
      'image',
      'paste',
      'clipboard',
      'drag',
      'drop',
      'upload',
      'paperclip',
    ],
    relatedIds: ['chat-sending', 'chat-artifacts'],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-sidebar',
    title: 'Sidebar Navigation',
    category: 'chat',
    summary: 'How to use the sidebar to navigate managers, sessions, and workers.',
    content: chatSidebarContent,
    keywords: [
      'sidebar',
      'navigation',
      'search',
      'profile',
      'session',
      'worker',
      'tree',
      'mobile',
      'hamburger',
    ],
    relatedIds: [
      'chat-sessions',
      'chat-profiles',
      'chat-workers',
      'chat-project-agents',
    ],
    contextKeys: ['chat.sidebar'],
  },
  {
    id: 'chat-sessions',
    title: 'Session Management',
    category: 'chat',
    summary: 'Creating, switching, renaming, and deleting sessions.',
    content: chatSessionsContent,
    keywords: [
      'session',
      'create',
      'switch',
      'rename',
      'delete',
      'stop',
      'resume',
      'clear',
      'new',
    ],
    relatedIds: ['chat-sidebar', 'chat-profiles', 'chat-fork-session'],
    contextKeys: ['chat.sidebar'],
  },
  {
    id: 'chat-profiles',
    title: 'Profiles',
    category: 'chat',
    summary: 'What profiles are and what they control.',
    content: chatProfilesContent,
    keywords: [
      'profile',
      'manager',
      'settings',
      'memory',
      'model',
      'config',
      'rename',
      'reorder',
    ],
    relatedIds: ['chat-sessions', 'chat-sidebar'],
    contextKeys: ['chat.sidebar'],
  },
  {
    id: 'chat-workers',
    title: 'Worker Agents',
    category: 'chat',
    summary: 'How worker pills, quick look, and worker monitoring work.',
    content: chatWorkersContent,
    keywords: [
      'worker',
      'pill',
      'quick look',
      'specialist',
      'badge',
      'streaming',
      'monitoring',
      'activity',
    ],
    relatedIds: ['chat-overview', 'chat-sidebar'],
    contextKeys: ['chat.workers'],
  },
  {
    id: 'chat-artifacts',
    title: 'Artifact Panel',
    category: 'chat',
    summary: 'How to view files and artifacts generated during a conversation.',
    content: chatArtifactsContent,
    keywords: [
      'artifact',
      'file',
      'panel',
      'viewer',
      'preview',
      'editor',
      'markdown',
      'code',
      'image',
    ],
    relatedIds: ['chat-overview', 'chat-attachments'],
    contextKeys: ['chat.artifacts'],
  },
  {
    id: 'chat-files',
    title: 'Files Workspace',
    category: 'chat',
    summary: 'How to use Files tabs, edit and preview content, manage paths, and protect drafts.',
    content: chatFilesContent,
    keywords: [
      'files',
      'file browser',
      'tabs',
      'preview tab',
      'sticky tab',
      'CodeMirror',
      'markdown preview',
      'source',
      'create file',
      'rename',
      'delete',
      'draft',
      'dirty edits',
      'save conflict',
      'worktree',
      'mobile',
    ],
    relatedIds: ['chat-overview', 'chat-source-control', 'chat-artifacts'],
    contextKeys: ['chat.artifacts'],
  },
  {
    id: 'chat-source-control',
    title: 'Source Control Workspace',
    category: 'chat',
    summary: 'How to review worktrees, branch changes, and pull requests from the Source Control workspace.',
    content: chatSourceControlContent,
    keywords: [
      'source control',
      'git',
      'changes',
      'history',
      'diff',
      'worktree',
      'branch',
      'fetch',
      'pull',
      'pull request',
      'github',
      'gh',
      'dirty edits',
      'file editing',
    ],
    relatedIds: ['chat-overview', 'chat-files', 'chat-artifacts'],
    contextKeys: ['chat.artifacts'],
  },
  {
    id: 'chat-fork-session',
    title: 'Forking Sessions',
    category: 'chat',
    summary: 'How to fork a session, including partial forks from a specific message.',
    content: chatForkSessionContent,
    keywords: [
      'fork',
      'branch',
      'copy',
      'partial',
      'duplicate',
      'checkpoint',
      'split',
    ],
    relatedIds: ['chat-sessions', 'chat-sidebar'],
    contextKeys: ['chat.fork'],
  },
  {
    id: 'chat-system-prompt',
    title: 'System Prompt Viewer',
    category: 'chat',
    summary: 'How to inspect the full runtime system prompt for the current session.',
    content: chatSystemPromptContent,
    keywords: [
      'system prompt',
      'runtime',
      'context',
      'viewer',
      'inspect',
      'bootstrap',
      'memory',
    ],
    relatedIds: ['chat-overview', 'chat-compaction'],
    contextKeys: ['chat.system-prompt'],
  },
  {
    id: 'chat-compaction',
    title: 'Context Compaction',
    category: 'chat',
    summary: 'What context compaction is, when to use it, and the difference between modes.',
    content: chatCompactionContent,
    keywords: [
      'compact',
      'compaction',
      'context',
      'token',
      'summary',
      'smart compact',
      'auto',
      'pin',
    ],
    relatedIds: ['chat-overview', 'chat-system-prompt'],
    contextKeys: ['chat.compaction'],
  },
  {
    id: 'chat-feedback',
    title: 'Message Feedback',
    category: 'chat',
    summary: 'How to rate messages and sessions with thumbs up/down and comments.',
    content: chatFeedbackContent,
    keywords: [
      'feedback',
      'rating',
      'thumbs',
      'upvote',
      'downvote',
      'comment',
      'reason',
      'vote',
    ],
    relatedIds: ['chat-overview'],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-project-agents',
    title: 'Creating and Using Project Agents',
    category: 'chat',
    summary: 'How to create project agents, message them, and manage their settings.',
    content: chatProjectAgentsContent,
    keywords: [
      'project agent',
      'create',
      'promotion',
      'agent creator',
      'wizard',
      'agent architect',
      'handle',
      '@mention',
      'messaging',
      'settings',
      'demote',
    ],
    relatedIds: ['concepts-project-agents', 'chat-sidebar', 'chat-sessions'],
    contextKeys: ['chat.sidebar', 'chat.main'],
  },
]
