import type { HelpArticle } from '../help-types'

import chatArtifactsContent from './articles/chat/chat-artifacts.md?raw'
import chatAttachmentsContent from './articles/chat/chat-attachments.md?raw'
import chatBrowserContent from './articles/chat/chat-browser.md?raw'
import chatCompactionContent from './articles/chat/chat-compaction.md?raw'
import chatFeedbackContent from './articles/chat/chat-feedback.md?raw'
import chatFilesContent from './articles/chat/chat-files.md?raw'
import chatForkSessionContent from './articles/chat/chat-fork-session.md?raw'
import chatOverviewContent from './articles/chat/chat-overview.md?raw'
import chatProfilesContent from './articles/chat/chat-profiles.md?raw'
import chatProjectAgentsContent from './articles/chat/chat-project-agents.md?raw'
import chatRestartRecoveryContent from './articles/chat/chat-restart-recovery.md?raw'
import chatSendingContent from './articles/chat/chat-sending.md?raw'
import chatSessionsContent from './articles/chat/chat-sessions.md?raw'
import chatSidebarContent from './articles/chat/chat-sidebar.md?raw'
import chatSourceControlContent from './articles/chat/chat-source-control.md?raw'
import chatSystemPromptContent from './articles/chat/chat-system-prompt.md?raw'
import chatThroughputContent from './articles/chat/chat-throughput.md?raw'
import chatWorkersContent from './articles/chat/chat-workers.md?raw'

export const chatArticles: HelpArticle[] = [
  {
    id: 'chat-overview',
    title: 'Chat Interface',
    category: 'chat',
    summary: 'How chat works, including streaming responses, the local Automatic Browser, workspace rail surfaces, and stopping agents.',
    content: chatOverviewContent,
    keywords: [
      'chat',
      'streaming',
      'throughput',
      'generation rate',
      'tok/s',
      'stop',
      'status',
      'channel',
      'context window',
      'overview',
      'working plan',
      'update plan',
      'source control',
      'worktree',
      'git',
      'files',
      'edit',
      'CodeMirror',
      'reply',
      'quote',
      'quoted preview',
      'reply target',
      'stall',
      'restart recovery',
      'resume all',
      'remote projects',
      'active origin',
      'embedded browser',
      'Chrome-backed tab',
      'automatic browser',
      'browser rail',
      'author chip',
      'viewer presence',
    ],
    relatedIds: [
      'settings-collaboration',
      'chat-sending',
      'chat-sidebar',
      'chat-compaction',
      'chat-browser',
      'chat-files',
      'chat-source-control',
      'chat-throughput',
      'chat-restart-recovery',
    ],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-browser',
    title: 'Automatic Browser',
    category: 'chat',
    summary: 'Use Forge’s Automatic Browser with embedded browser and Chrome-backed tabs.',
    content: chatBrowserContent,
    keywords: [
      'browser',
      'embedded browser',
      'Chrome-backed tab',
      'chrome extension',
      'load unpacked',
      'Chrome setup',
      'automatic browser',
      'desktop',
      'webview',
      'tabs',
      'screenshot',
      'recording',
      'viewport',
      'agent control',
      'human control',
      'Take Control',
      'fresh snapshot',
      'attached-idle',
      'pointer movement',
      'navigation retention',
      'DevTools',
      'debugger interruption',
      'timeout',
      'no replay',
      'unavailable host',
      'agent-browser',
      'remote projects',
      'collaboration',
    ],
    relatedIds: ['chat-overview', 'settings-external-chrome', 'settings-collaboration', 'settings-skills'],
    contextKeys: ['chat.browser', 'chat.main'],
  },
  {
    id: 'chat-sending',
    title: 'Sending Messages',
    category: 'chat',
    summary: 'How to send messages, change the session model, format text, and use shortcuts or slash commands.',
    content: chatSendingContent,
    keywords: [
      'send',
      'enter',
      'format',
      'slash',
      'command',
      'draft',
      'voice',
      'microphone',
      'keyboard',
      'reply',
      'quote',
      'quoted preview',
      'reply target',
      'session model',
      'model picker',
      'model pill',
      'reasoning level',
      'override session model',
      'use project default',
    ],
    relatedIds: ['chat-overview', 'chat-attachments', 'models-routing'],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-attachments',
    title: 'Attachments',
    category: 'chat',
    summary: 'How to attach files and images to messages.',
    content: chatAttachmentsContent,
    keywords: [
      'attach',
      'file',
      'image',
      'paste',
      'clipboard',
      'drag',
      'drop',
      'upload',
      'paperclip',
    ],
    relatedIds: ['chat-sending', 'chat-artifacts'],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-sidebar',
    title: 'Sidebar Navigation',
    category: 'chat',
    summary: 'How to use the sidebar to navigate managers, sessions, and workers.',
    content: chatSidebarContent,
    keywords: [
      'sidebar',
      'navigation',
      'search',
      'profile',
      'session',
      'worker',
      'tree',
      'mobile',
      'hamburger',
      'remote projects',
      'globe',
      'connection status',
    ],
    relatedIds: [
      'settings-collaboration',
      'chat-sessions',
      'chat-profiles',
      'chat-workers',
      'chat-project-agents',
    ],
    contextKeys: ['chat.sidebar'],
  },
  {
    id: 'chat-sessions',
    title: 'Session Management',
    category: 'chat',
    summary: 'Creating, switching, renaming, and deleting sessions.',
    content: chatSessionsContent,
    keywords: [
      'session',
      'create',
      'switch',
      'rename',
      'delete',
      'stop',
      'resume',
      'clear',
      'new',
    ],
    relatedIds: ['chat-sidebar', 'chat-profiles', 'chat-fork-session'],
    contextKeys: ['chat.sidebar'],
  },
  {
    id: 'chat-profiles',
    title: 'Profiles',
    category: 'chat',
    summary: 'What profiles are and what they control.',
    content: chatProfilesContent,
    keywords: [
      'profile',
      'manager',
      'settings',
      'memory',
      'model',
      'config',
      'rename',
      'reorder',
      'remote profile',
      'remote projects',
    ],
    relatedIds: ['settings-collaboration', 'chat-sessions', 'chat-sidebar'],
    contextKeys: ['chat.sidebar'],
  },
  {
    id: 'chat-workers',
    title: 'Worker Agents',
    category: 'chat',
    summary: 'How worker pills, quick look, final Pi response throughput, and worker monitoring work.',
    content: chatWorkersContent,
    keywords: [
      'worker',
      'pill',
      'quick look',
      'specialist',
      'badge',
      'streaming',
      'monitoring',
      'activity',
      'throughput',
      'generation rate',
      'tok/s',
    ],
    relatedIds: ['chat-overview', 'chat-sidebar', 'chat-throughput'],
    contextKeys: ['chat.workers'],
  },
  {
    id: 'chat-throughput',
    title: 'Response Throughput',
    category: 'chat',
    summary: 'Understand final Pi response throughput across full requests and history in Stats → Response throughput.',
    content: chatThroughputContent,
    keywords: [
      'throughput',
      'response throughput',
      'full request duration',
      'generation throughput',
      'tok/s',
      'tokens per second',
      'provider final',
      'final throughput',
      'stats',
      'trend',
      'time to first token',
      'TTFT',
      'Pi runtime',
      'worker throughput',
      'manager throughput',
      'strict boundaries',
      'all measured',
    ],
    relatedIds: ['chat-overview', 'chat-workers', 'chat-fork-session'],
    contextKeys: ['chat.main', 'chat.workers'],
  },
  {
    id: 'chat-restart-recovery',
    title: 'Stalls and restart recovery',
    category: 'chat',
    summary: 'What manager stall notices mean and how to recover interrupted work after a backend restart.',
    content: chatRestartRecoveryContent,
    keywords: [
      'stall',
      'silence',
      'watchdog',
      'restart',
      'recovery',
      'resume all',
      'dismiss',
      'stop all',
      'interrupted',
    ],
    relatedIds: ['chat-overview', 'chat-workers', 'chat-sessions'],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-artifacts',
    title: 'Artifact Panel',
    category: 'chat',
    summary: 'How to view files and artifacts generated during a conversation.',
    content: chatArtifactsContent,
    keywords: [
      'artifact',
      'file',
      'panel',
      'viewer',
      'preview',
      'editor',
      'markdown',
      'code',
      'image',
    ],
    relatedIds: ['chat-overview', 'chat-attachments'],
    contextKeys: ['chat.artifacts'],
  },
  {
    id: 'chat-files',
    title: 'Files Workspace',
    category: 'chat',
    summary: 'How to use Files tabs, edit and preview content, manage paths, and protect drafts.',
    content: chatFilesContent,
    keywords: [
      'files',
      'file browser',
      'tabs',
      'preview tab',
      'sticky tab',
      'CodeMirror',
      'markdown preview',
      'source',
      'create file',
      'rename',
      'delete',
      'draft',
      'dirty edits',
      'save conflict',
      'worktree',
      'mobile',
      'remote projects',
      'remote files',
      'server storage',
    ],
    relatedIds: ['settings-collaboration', 'chat-overview', 'chat-source-control', 'chat-artifacts'],
    contextKeys: ['chat.artifacts'],
  },
  {
    id: 'chat-source-control',
    title: 'Source Control Workspace',
    category: 'chat',
    summary: 'How to review worktrees, branch changes, and pull requests from the Source Control workspace.',
    content: chatSourceControlContent,
    keywords: [
      'source control',
      'git',
      'changes',
      'history',
      'diff',
      'worktree',
      'branch',
      'fetch',
      'pull',
      'pull request',
      'github',
      'gh',
      'dirty edits',
      'file editing',
      'remote projects',
      'remote git',
      'server repository',
    ],
    relatedIds: ['settings-collaboration', 'chat-overview', 'chat-files', 'chat-artifacts'],
    contextKeys: ['chat.artifacts'],
  },
  {
    id: 'chat-fork-session',
    title: 'Forking Sessions',
    category: 'chat',
    summary: 'How to fork a session, including partial forks from a specific message.',
    content: chatForkSessionContent,
    keywords: [
      'fork',
      'branch',
      'copy',
      'partial',
      'duplicate',
      'checkpoint',
      'split',
    ],
    relatedIds: ['chat-sessions', 'chat-sidebar', 'chat-throughput'],
    contextKeys: ['chat.fork'],
  },
  {
    id: 'chat-system-prompt',
    title: 'Initial Model Input Viewer',
    category: 'chat',
    summary: 'How to inspect the initial Pi model input captured for the current session.',
    content: chatSystemPromptContent,
    keywords: [
      'system prompt',
      'runtime',
      'context',
      'viewer',
      'inspect',
      'bootstrap',
      'memory',
    ],
    relatedIds: ['chat-overview', 'chat-compaction'],
    contextKeys: ['chat.system-prompt'],
  },
  {
    id: 'chat-compaction',
    title: 'Context Compaction',
    category: 'chat',
    summary: 'What context compaction is, when to use it, and the difference between modes.',
    content: chatCompactionContent,
    keywords: [
      'compact',
      'compaction',
      'context',
      'token',
      'summary',
      'smart compact',
      'auto',
      'pin',
    ],
    relatedIds: ['chat-overview', 'chat-system-prompt'],
    contextKeys: ['chat.compaction'],
  },
  {
    id: 'chat-feedback',
    title: 'Message Feedback',
    category: 'chat',
    summary: 'How to rate messages and sessions with thumbs up/down and comments.',
    content: chatFeedbackContent,
    keywords: [
      'feedback',
      'rating',
      'thumbs',
      'upvote',
      'downvote',
      'comment',
      'reason',
      'vote',
    ],
    relatedIds: ['chat-overview'],
    contextKeys: ['chat.main'],
  },
  {
    id: 'chat-project-agents',
    title: 'Creating and Using Project Agents',
    category: 'chat',
    summary: 'How to create project agents, message them, and manage their settings.',
    content: chatProjectAgentsContent,
    keywords: [
      'project agent',
      'create',
      'promotion',
      'agent creator',
      'wizard',
      'agent architect',
      'handle',
      '@mention',
      'messaging',
      'settings',
      'demote',
    ],
    relatedIds: ['concepts-project-agents', 'chat-sidebar', 'chat-sessions'],
    contextKeys: ['chat.sidebar', 'chat.main'],
  },
]
