import type { HelpArticle } from '../help-types'

import gettingStartedConfigurationContent from './articles/getting-started/getting-started-configuration.md?raw'
import gettingStartedContent from './articles/getting-started/getting-started.md?raw'
import gettingStartedFirstSessionContent from './articles/getting-started/getting-started-first-session.md?raw'
import gettingStartedHelpContent from './articles/getting-started/getting-started-help.md?raw'

export const gettingStartedArticles: HelpArticle[] = [
  {
    id: 'getting-started',
    title: 'Welcome to Forge',
    category: 'getting-started',
    summary: 'What Forge does and how to start using it.',
    content: gettingStartedContent,
    keywords: [
      'welcome',
      'getting started',
      'overview',
      'introduction',
      'first steps',
      'new user',
      'onboarding',
    ],
    relatedIds: ['getting-started-first-session', 'getting-started-configuration', 'getting-started-help'],
    contextKeys: ['chat.main', 'chat.sidebar'],
  },
  {
    id: 'getting-started-first-session',
    title: 'Your First Chat Session',
    category: 'getting-started',
    summary: 'Create a manager, send a message, and see how Work Mode owns or delegates execution.',
    content: gettingStartedFirstSessionContent,
    keywords: [
      'first session',
      'create project',
      'new project',
      'send message',
      'workers',
      'worker pills',
      'sessions',
      'profiles',
      'chat',
      'work mode',
      'delegate first',
      'adaptive',
      'hands-on',
    ],
    relatedIds: [
      'getting-started',
      'getting-started-configuration',
      'chat-overview',
      'concepts-multi-agent',
      'concepts-specialists',
      'concepts-working-plans',
      'concepts-goals',
      'concepts-project-agents',
    ],
    contextKeys: ['chat.main', 'chat.sidebar'],
  },
  {
    id: 'getting-started-configuration',
    title: 'Essential Setup',
    category: 'getting-started',
    summary: 'Connect a provider, choose a model, and configure your profile.',
    content: gettingStartedConfigurationContent,
    keywords: [
      'setup',
      'configuration',
      'auth',
      'authentication',
      'api key',
      'oauth',
      'model',
      'provider',
      'anthropic',
      'openai',
      'xai',
      'grok',
      'device code',
      'headless',
      'callback url',
      'copy url',
      'cancel oauth',
      'profile',
      'settings',
      'specialists',
      'manager model',
      'manager selector',
      'per-session override',
      'worker-only entitlement',
      'remote projects',
      'collaboration connection',
      'remote server',
    ],
    relatedIds: [
      'settings-collaboration',
      'getting-started',
      'getting-started-first-session',
      'settings-auth',
      'settings-oauth',
      'settings-general',
      'models-overview',
      'models-providers',
    ],
    contextKeys: ['settings.auth', 'settings.general'],
  },
  {
    id: 'getting-started-help',
    title: 'Using the Help System',
    category: 'getting-started',
    summary: 'Find answers with the help drawer, keyboard shortcuts, and search.',
    content: gettingStartedHelpContent,
    keywords: [
      'help',
      'documentation',
      'docs',
      'search',
      'keyboard shortcuts',
      'shortcuts',
      'help drawer',
      'context help',
      'how to',
      'find',
    ],
    relatedIds: ['getting-started'],
    contextKeys: ['chat.main', 'settings.general'],
  },
]
