import type { HelpArticle } from '../help-types'

import modelsCostContent from './articles/models/models-cost.md?raw'
import modelsOverviewContent from './articles/models/models-overview.md?raw'
import modelsProvidersContent from './articles/models/models-providers.md?raw'
import modelsReasoningContent from './articles/models/models-reasoning.md?raw'
import modelsRoutingContent from './articles/models/models-routing.md?raw'

const modelsOverview: HelpArticle = {
  id: 'models-overview',
  title: 'Understanding Models in Forge',
  category: 'models',
  summary: 'How Forge uses different AI models and how to pick the right one for your work.',
  content: modelsOverviewContent,
  keywords: [
    'model',
    'models',
    'select',
    'choose',
    'AI',
    'provider',
    'overview',
  ],
  relatedIds: ['models-providers', 'models-reasoning', 'models-routing'],
  contextKeys: ['settings.general', 'settings.models', 'settings.specialists'],
}

const modelsProviders: HelpArticle = {
  id: 'models-providers',
  title: 'Provider Guide',
  category: 'models',
  summary: 'What each AI provider offers and when to use their models.',
  content: modelsProvidersContent,
  keywords: [
    'provider',
    'OpenAI',
    'Codex',
    'Anthropic',
    'Claude',
    'Grok',
    'xAI',
    'xAI OAuth',
    'API key',
    'grok-4.6',
    'grok-4.5',
    'grok-build',
    'grok-composer-2.5-fast',
    'OAuth entitlement',
    'model discovery',
    'device code',
    'headless',
    'callback URL',
    'copy URL',
    'specialist',
    'spawn',
    'manager',
    'manager model',
    'per-session override',
    'OpenRouter',
    'supportsTools',
    'tool calls',
    'managerEnabled',
    'exact model ID',
    'legacy',
    'unverified',
    'credential',
    'model visibility',
    'GPT',
    'GPT-5.6',
    'Sol',
    'Terra',
    'Luna',
    'Opus',
    'Sonnet',
    'Haiku',
  ],
  relatedIds: ['models-overview', 'models-cost', 'models-reasoning', 'settings-auth', 'settings-oauth', 'getting-started-configuration'],
  contextKeys: ['settings.general', 'settings.models', 'settings.auth', 'settings.specialists'],
}

const modelsReasoning: HelpArticle = {
  id: 'models-reasoning',
  title: 'Reasoning Levels Explained',
  category: 'models',
  summary: 'What each reasoning level does and when to raise or lower it.',
  content: modelsReasoningContent,
  keywords: [
    'reasoning',
    'level',
    'none',
    'low',
    'medium',
    'high',
    'xhigh',
    'max',
    'ultra',
    'thinking',
    'quality',
  ],
  relatedIds: ['models-overview', 'models-cost', 'models-providers'],
  contextKeys: ['settings.general', 'settings.models', 'settings.specialists'],
}

const modelsRouting: HelpArticle = {
  id: 'models-routing',
  title: 'How Model Routing Works',
  category: 'models',
  summary: 'How session models, work mode, task types, delegation presets, model policies, and fallbacks determine which model runs work.',
  content: modelsRoutingContent,
  keywords: [
    'routing',
    'specialist',
    'fallback',
    'delegation',
    'worker roster',
    'execution profile',
    'worker profile',
    'model policy',
    'delegation preset',
    'work mode',
    'manager',
    'worker',
    'spawn',
    'session model',
    'composer pill',
    'override session model',
    'use project default',
    'reasoning level',
    'xAI entitlement',
    'OAuth-only model',
    'OpenRouter',
    'supportsTools',
    'tool calls',
    'managerEnabled',
    'exact model ID',
    'legacy',
    'unverified',
    'credential',
    'manager model',
    'per-session override',
    'compaction',
    'fail closed',
  ],
  relatedIds: ['models-overview', 'models-providers', 'concepts-specialists', 'chat-sending'],
  contextKeys: ['settings.models', 'settings.specialists', 'chat.workers', 'chat.main'],
}

const modelsCost: HelpArticle = {
  id: 'models-cost',
  title: 'Cost and Speed Tradeoffs',
  category: 'models',
  summary: 'Which models are fast and cheap versus slow and thorough.',
  content: modelsCostContent,
  keywords: [
    'cost',
    'speed',
    'fast',
    'cheap',
    'expensive',
    'tradeoff',
    'token',
    'latency',
    'price',
  ],
  relatedIds: ['models-overview', 'models-reasoning', 'models-routing'],
  contextKeys: ['settings.general', 'settings.models', 'settings.specialists'],
}

export const modelsArticles: HelpArticle[] = [
  modelsOverview,
  modelsProviders,
  modelsReasoning,
  modelsRouting,
  modelsCost,
]
