import type { HelpArticle } from '../help-types'

import settingsAboutContent from './articles/settings/settings-about.md?raw'
import settingsAuthContent from './articles/settings/settings-auth.md?raw'
import settingsCliAccessContent from './articles/settings/settings-cli-access.md?raw'
import settingsCollaborationContent from './articles/settings/settings-collaboration.md?raw'
import settingsEditorContent from './articles/settings/settings-editor.md?raw'
import settingsExtensionsContent from './articles/settings/settings-extensions.md?raw'
import settingsGeneralContent from './articles/settings/settings-general.md?raw'
import settingsIntegrationsContent from './articles/settings/settings-integrations.md?raw'
import settingsNotificationsContent from './articles/settings/settings-notifications.md?raw'
import settingsObservabilityContent from './articles/settings/settings-observability.md?raw'
import settingsOauthContent from './articles/settings/settings-oauth.md?raw'
import settingsPromptsContent from './articles/settings/settings-prompts.md?raw'
import settingsSkillsContent from './articles/settings/settings-skills.md?raw'
import settingsSlashCommandsContent from './articles/settings/settings-slash-commands.md?raw'
import settingsSpecialistsContent from './articles/settings/settings-specialists.md?raw'
import settingsTelegramContent from './articles/settings/settings-telegram.md?raw'
import settingsThemeContent from './articles/settings/settings-theme.md?raw'

export const settingsArticles: HelpArticle[] = [
  {
    id: 'settings-general',
    title: 'General Settings',
    category: 'settings',
    summary: 'Editor, sidebar, compaction, Cortex consolidation, Knowledge v2 activation, and related settings.',
    content: settingsGeneralContent,
    keywords: [
      'theme',
      'dark mode',
      'light mode',
      'editor',
      'vscode',
      'cursor',
      'cortex',
      'consolidation',
      'knowledge v2',
      'migration',
      'reboot',
      'appearance',
      'onboarding',
      'preferences',
      'sidebar',
      'provider usage',
      'subscription',
      'usage monitoring',
      'compaction',
      'smart compact',
      'reasoning',
      'timeout',
      'observability',
      'phoenix',
      'diagnostics',
    ],
    relatedIds: ['settings-theme', 'settings-editor', 'settings-collaboration', 'settings-observability', 'settings-about', 'chat-compaction', 'models-providers'],
    contextKeys: ['settings.general'],
  },
  {
    id: 'settings-theme',
    title: 'Theme and Appearance',
    category: 'settings',
    summary: 'Switch modes, preview templates, and apply local color/font customization.',
    content: settingsThemeContent,
    keywords: [
      'theme',
      'dark mode',
      'light mode',
      'system',
      'appearance',
      'color scheme',
    ],
    relatedIds: ['settings-general'],
    contextKeys: ['settings.general', 'settings.appearance'],
  },
  {
    id: 'settings-editor',
    title: 'Editor Preference',
    category: 'settings',
    summary: 'Choose which code editor opens artifact files.',
    content: settingsEditorContent,
    keywords: [
      'editor',
      'vscode',
      'cursor',
      'artifact',
      'file',
      'open',
      'code',
    ],
    relatedIds: ['settings-general'],
    contextKeys: ['settings.general'],
  },
  {
    id: 'settings-auth',
    title: 'Authentication',
    category: 'settings',
    summary: 'Configure provider credentials and auth modes.',
    content: settingsAuthContent,
    keywords: [
      'api key',
      'authentication',
      'anthropic',
      'openai',
      'xai',
      'grok',
      'oauth',
      'credentials',
      'login',
    ],
    relatedIds: ['settings-oauth'],
    contextKeys: ['settings.auth'],
  },
  {
    id: 'settings-collaboration',
    title: 'Collaboration and Remote Projects',
    category: 'settings',
    summary: 'Connect Forge servers, sign in, and open remote projects safely from the unified Builder sidebar.',
    content: settingsCollaborationContent,
    keywords: [
      'collaboration',
      'remote projects',
      'remote server',
      'connection',
      'server url',
      'sign in',
      'remote sidebar',
      'globe',
      'active origin',
      'presence',
      'remote files',
      'remote git',
      'remote terminal',
      'trusted members',
      'protocol version',
      'unreachable',
    ],
    relatedIds: ['chat-sidebar', 'chat-overview', 'terminal-overview', 'settings-auth'],
    contextKeys: ['settings.collaboration'],
  },
  {
    id: 'settings-observability',
    title: 'Phoenix Observability',
    category: 'settings',
    summary: 'Export local Forge traces to Arize Phoenix with redaction, caps, and capture controls.',
    content: settingsObservabilityContent,
    keywords: [
      'observability',
      'phoenix',
      'arize',
      'otlp',
      'traces',
      'protobuf',
      'redaction',
      'privacy',
      'diagnostics',
      'export',
      'span',
    ],
    relatedIds: ['settings-general', 'settings-about'],
    contextKeys: ['settings.observability'],
  },
  {
    id: 'settings-oauth',
    title: 'OAuth Login',
    category: 'settings',
    summary: 'Authorize Forge with your provider account through OAuth.',
    content: settingsOauthContent,
    keywords: [
      'oauth',
      'login',
      'authorize',
      'token',
      'anthropic',
      'openai',
      'browser',
      'authentication',
    ],
    relatedIds: ['settings-auth'],
    contextKeys: ['settings.auth'],
  },
  {
    id: 'settings-notifications',
    title: 'Notification Sounds',
    category: 'settings',
    summary: 'Set up sound alerts per manager and upload custom sounds.',
    content: settingsNotificationsContent,
    keywords: [
      'notifications',
      'sound',
      'alert',
      'audio',
      'unread',
      'done',
      'custom sound',
      'volume',
      'manager',
      'cli',
      'mute',
    ],
    relatedIds: ['settings-general'],
    contextKeys: ['settings.notifications'],
  },
  {
    id: 'settings-integrations',
    title: 'Integrations',
    category: 'settings',
    summary: 'Connect external services like Telegram to Forge.',
    content: settingsIntegrationsContent,
    keywords: [
      'integrations',
      'telegram',
      'external',
      'messaging',
      'bot',
      'scope',
      'shared',
      'profile',
    ],
    relatedIds: ['settings-telegram'],
    contextKeys: ['settings.integrations'],
  },
  {
    id: 'settings-telegram',
    title: 'Telegram Bot Setup',
    category: 'settings',
    summary: 'Connect a Telegram bot to send and receive messages through Forge.',
    content: settingsTelegramContent,
    keywords: [
      'telegram',
      'bot',
      'botfather',
      'token',
      'polling',
      'attachments',
      'messaging',
      'integration',
      'allowed users',
    ],
    relatedIds: ['settings-integrations'],
    contextKeys: ['settings.integrations'],
  },
  {
    id: 'settings-skills',
    title: 'Skills Management',
    category: 'settings',
    summary: 'Configure skills, share user-created bundles, and import skills from links.',
    content: settingsSkillsContent,
    keywords: [
      'skills',
      'api key',
      'environment variable',
      'brave',
      'chrome',
      'cdp',
      'image generation',
      'configuration',
      'secrets',
      'share',
      'import',
      'url',
      'deep link',
      'preview',
      'conflict',
      'collaboration',
      'channel',
      'category',
      'selection',
    ],
    relatedIds: ['settings-auth', 'settings-extensions', 'settings-specialists'],
    contextKeys: ['settings.skills'],
  },
  {
    id: 'settings-prompts',
    title: 'Prompt System',
    category: 'settings',
    summary: 'Edit system prompts, preview runtime context, and manage Cortex surfaces.',
    content: settingsPromptsContent,
    keywords: [
      'prompts',
      'system prompt',
      'archetype',
      'operational',
      'cortex',
      'override',
      'preview',
      'runtime context',
      'profile',
    ],
    relatedIds: ['settings-specialists'],
    contextKeys: ['settings.prompts'],
  },
  {
    id: 'settings-specialists',
    title: 'Specialist Workers',
    category: 'settings',
    summary: 'Create named worker personas with specific models, prompts, and fallback routing.',
    content: settingsSpecialistsContent,
    keywords: [
      'specialists',
      'workers',
      'model',
      'reasoning',
      'fallback',
      'prompt',
      'roster',
      'pinned',
      'override',
      'template',
    ],
    relatedIds: ['settings-prompts'],
    contextKeys: ['settings.specialists'],
  },
  {
    id: 'settings-slash-commands',
    title: 'Slash Commands',
    category: 'settings',
    summary: 'Create saved prompt shortcuts accessible with / in chat.',
    content: settingsSlashCommandsContent,
    keywords: [
      'slash commands',
      'shortcuts',
      'prompt',
      'autocomplete',
      'chat',
      'command',
      'saved prompt',
    ],
    relatedIds: ['settings-general'],
    contextKeys: ['settings.slash-commands'],
  },
  {
    id: 'settings-extensions',
    title: 'Extensions',
    category: 'settings',
    summary: 'View and manage Pi extensions that add custom tools and event hooks.',
    content: settingsExtensionsContent,
    keywords: [
      'extensions',
      'plugins',
      'tools',
      'events',
      'custom',
      'discovery',
      'runtime',
      'pi',
    ],
    relatedIds: ['settings-skills'],
    contextKeys: ['settings.extensions'],
  },
  {
    id: 'settings-cli-access',
    title: 'CLI Access',
    category: 'settings',
    summary: 'Generate CLI keys, install the desktop shim, and configure headless automation.',
    content: settingsCliAccessContent,
    keywords: [
      'cli',
      'command line',
      'headless',
      'automation',
      'api key',
      'bearer',
      'install',
      'path',
      'rotate',
      'revoke',
    ],
    relatedIds: ['settings-auth', 'settings-general'],
    contextKeys: ['settings.cli-access'],
  },
  {
    id: 'settings-about',
    title: 'About Forge',
    category: 'settings',
    summary: 'Version info, update checks, and release channel settings.',
    content: settingsAboutContent,
    keywords: [
      'about',
      'version',
      'update',
      'release',
      'beta',
      'electron',
      'desktop',
      'changelog',
    ],
    relatedIds: ['settings-general'],
    contextKeys: ['settings.about'],
  },
]
