import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import type { VersioningCommitEvent } from "../swarm/forge-extension-types.js";
import { GitCli } from "./git-cli.js";
import {
  enumerateExistingTrackedPaths,
  isTrackedVersionedPath,
  resolveVersionedPathMetadata,
  type VersionedPathsOptions
} from "./versioned-paths.js";
import type { VersioningMutation, VersioningMutationSink } from "./versioning-types.js";

const DEFAULT_DEBOUNCE_MS = 1_500;
const DEFAULT_RECONCILE_INTERVAL_MS = 5 * 60 * 1_000;
const MIN_GIT_MAJOR = 2;
const MIN_GIT_MINOR = 20;
const EXCLUDE_FILE_CONTENT = [
  "# Auto-generated by Forge versioning. Do not edit.",
  "# Everything is excluded by default; only explicitly forced pathspecs are staged.",
  "*",
  "*.bak*",
  ""
].join("\n");

interface LoggerLike {
  info(message: string): void;
  warn(message: string): void;
  error(message: string): void;
}

export interface EmbeddedGitVersioningServiceOptions extends VersionedPathsOptions {
  dataDir: string;
  enabled?: boolean;
  debounceMs?: number;
  reconcileIntervalMs?: number;
  gitBinary?: string;
  logger?: Partial<LoggerLike>;
  onCommit?: (event: VersioningCommitEvent) => Promise<void> | void;
}

export class EmbeddedGitVersioningService implements VersioningMutationSink {
  private readonly dataDir: string;
  private readonly debounceMs: number;
  private readonly reconcileIntervalMs: number;
  private readonly git: GitCli;
  private readonly logger: LoggerLike;
  private readonly trackSessionMemory: boolean;
  private readonly onCommit?: (event: VersioningCommitEvent) => Promise<void> | void;

  private enabled: boolean;
  private started = false;
  private readonly pendingMutations = new Map<string, VersioningMutation>();
  private flushTimer: NodeJS.Timeout | undefined;
  private reconcileTimer: NodeJS.Timeout | undefined;
  private gitOperationQueue: Promise<void> = Promise.resolve();

  constructor(options: EmbeddedGitVersioningServiceOptions) {
    this.dataDir = resolve(options.dataDir);
    this.enabled =
      options.enabled ??
      parseEnabledEnv(process.env.FORGE_VERSIONING_ENABLED ?? process.env.MIDDLEMAN_VERSIONING_ENABLED);
    this.debounceMs = options.debounceMs ?? DEFAULT_DEBOUNCE_MS;
    this.reconcileIntervalMs = options.reconcileIntervalMs ?? parseReconcileIntervalEnv();
    this.git = new GitCli({
      cwd: this.dataDir,
      gitBinary: options.gitBinary
    });
    this.logger = {
      info: options.logger?.info ?? ((message) => console.log(message)),
      warn: options.logger?.warn ?? ((message) => console.warn(message)),
      error: options.logger?.error ?? ((message) => console.error(message))
    };
    this.trackSessionMemory = options.trackSessionMemory ?? parseTrackSessionMemoryEnv();
    this.onCommit = options.onCommit;
  }

  async start(): Promise<void> {
    if (this.started || !this.enabled) {
      return;
    }

    try {
      await mkdir(this.dataDir, { recursive: true });
      await this.verifyGitAvailability();
      await this.ensureRepositoryInitialized();
      this.started = true;

      await this.reconcileNow("startup");

      if (this.reconcileIntervalMs > 0) {
        this.reconcileTimer = setInterval(() => {
          void this.reconcileNow("interval").catch((error) => {
            this.handleBackgroundFailure("interval reconcile", error);
          });
        }, this.reconcileIntervalMs);
      }
    } catch (error) {
      this.disable(error instanceof Error ? error.message : String(error));
    }
  }

  async stop(): Promise<void> {
    if (this.flushTimer) {
      clearTimeout(this.flushTimer);
      this.flushTimer = undefined;
    }

    if (this.reconcileTimer) {
      clearInterval(this.reconcileTimer);
      this.reconcileTimer = undefined;
    }

    if (!this.started) {
      return;
    }

    try {
      await this.flushPending("shutdown");
    } catch (error) {
      this.logger.warn(`[versioning] Failed to flush pending changes on shutdown: ${stringifyError(error)}`);
    }

    this.started = false;
  }

  isTrackedPath(path: string): boolean {
    return isTrackedVersionedPath(this.dataDir, path, { trackSessionMemory: this.trackSessionMemory });
  }

  async recordMutation(mutation: VersioningMutation): Promise<boolean> {
    if (!this.started || !this.enabled) {
      return false;
    }

    const metadata = resolveVersionedPathMetadata(this.dataDir, mutation.path, {
      trackSessionMemory: this.trackSessionMemory
    });
    if (!metadata) {
      return false;
    }

    this.pendingMutations.set(metadata.relativePath, {
      ...mutation,
      path: metadata.relativePath,
      profileId: mutation.profileId ?? metadata.profileId,
      sessionId: mutation.sessionId ?? metadata.sessionId,
      promptCategory: mutation.promptCategory ?? metadata.promptCategory,
      promptId: mutation.promptId ?? metadata.promptId
    });
    this.scheduleDebouncedFlush();
    return true;
  }

  async flushPending(reason: string): Promise<void> {
    if (!this.started || !this.enabled) {
      return;
    }

    await this.enqueueGitOperation(async () => {
      this.clearFlushTimer();
      const pending = this.getPendingMutationEntriesSnapshot();
      if (pending.length === 0) {
        return;
      }

      await this.stageAndCommit({
        explicitPaths: pending.map(([, mutation]) => mutation.path),
        mutations: pending.map(([, mutation]) => mutation),
        reason
      });
      this.deletePendingMutationEntries(pending);
    });
  }

  async reconcileNow(reason: string): Promise<void> {
    if (!this.started || !this.enabled) {
      return;
    }

    await this.enqueueGitOperation(async () => {
      this.clearFlushTimer();
      const pending = this.getPendingMutationEntriesSnapshot();
      const existingTrackedPaths = await enumerateExistingTrackedPaths(this.dataDir, {
        trackSessionMemory: this.trackSessionMemory
      });
      const indexedTrackedPaths = await this.listIndexedTrackedPaths();
      const explicitPaths = Array.from(
        new Set([...existingTrackedPaths, ...indexedTrackedPaths, ...pending.map(([, mutation]) => mutation.path)])
      );

      await this.stageAndCommit({
        explicitPaths,
        indexedTrackedPaths,
        mutations: pending.map(([, mutation]) => ({
          ...mutation,
          source: reason === "startup" ? "bootstrap" : mutation.source
        })),
        reason,
        defaultSource: reason === "startup" ? "bootstrap" : "reconcile"
      });
      this.deletePendingMutationEntries(pending);
    });
  }

  private async stageAndCommit(options: {
    explicitPaths: string[];
    indexedTrackedPaths?: Set<string>;
    mutations: VersioningMutation[];
    reason: string;
    defaultSource?: VersioningMutation["source"];
  }): Promise<void> {
    const indexedTrackedPaths = options.indexedTrackedPaths ?? await this.listIndexedTrackedPaths();
    const stageablePaths = await this.filterStageablePaths(options.explicitPaths, indexedTrackedPaths);
    if (stageablePaths.length === 0) {
      return;
    }

    await this.git.run(["add", "-f", "-A", "--", ...stageablePaths]);
    const diff = await this.git.run(["diff", "--cached", "--name-only", "--", ...stageablePaths]);
    const stagedPaths = diff.stdout
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .sort((left, right) => left.localeCompare(right));

    if (stagedPaths.length === 0) {
      return;
    }

    const normalizedMutations = stagedPaths.map((path) => {
      const explicit = options.mutations.find((mutation) => mutation.path === path);
      if (explicit) {
        return explicit;
      }

      const metadata = resolveVersionedPathMetadata(this.dataDir, join(this.dataDir, path), {
        trackSessionMemory: this.trackSessionMemory
      });
      return {
        path,
        action: indexedTrackedPaths.has(path) ? "delete" : "write",
        source: options.defaultSource ?? "reconcile",
        profileId: metadata?.profileId,
        sessionId: metadata?.sessionId,
        promptCategory: metadata?.promptCategory,
        promptId: metadata?.promptId
      } satisfies VersioningMutation;
    });

    const message = await this.buildCommitMessage(stagedPaths, normalizedMutations, options.reason);
    await this.git.run(["commit", "--quiet", "-m", message.subject, ...(message.body ? ["-m", message.body] : [])]);

    const commitSha = (await this.git.run(["rev-parse", "HEAD"]))
      .stdout
      .trim();
    const profileIds = Array.from(
      new Set(
        normalizedMutations
          .map((mutation) => mutation.profileId)
          .filter((value): value is string => Boolean(value))
      )
    ).sort((left, right) => left.localeCompare(right));

    const commitEvent: VersioningCommitEvent = {
      sha: commitSha,
      subject: message.subject,
      body: message.body,
      paths: stagedPaths,
      mutations: normalizedMutations,
      reason: options.reason,
      profileIds
    };

    if (this.onCommit) {
      try {
        await this.onCommit(commitEvent);
      } catch (error) {
        this.logger.warn(`[versioning] Post-commit observer failed: ${stringifyError(error)}`);
      }
    }
  }

  private async buildCommitMessage(
    stagedPaths: string[],
    mutations: VersioningMutation[],
    reason: string
  ): Promise<{ subject: string; body: string }> {
    const uniqueSources = Array.from(new Set(mutations.map((mutation) => mutation.source)));
    const uniqueProfiles = Array.from(
      new Set(mutations.map((mutation) => mutation.profileId).filter((value): value is string => Boolean(value)))
    );
    const primary = mutations[0];
    const fileCountLabel = `${stagedPaths.length} tracked file${stagedPaths.length === 1 ? "" : "s"}`;
    const hasHead = await this.hasHead();

    let subject = hasHead ? `versioning: update ${fileCountLabel}` : "versioning: bootstrap tracked files";
    if (!hasHead || reason === "startup") {
      subject = hasHead ? subject : "versioning: bootstrap tracked files";
    } else if (uniqueSources.length === 1 && primary) {
      switch (primary.source) {
        case "profile-memory-merge":
          subject = `memory(${primary.profileId ?? "unknown"}): merge session ${primary.sessionId ?? "unknown"}`;
          break;
        case "prompt-save":
          subject = `prompt(${primary.profileId ?? "unknown"}): save ${primary.promptCategory ?? "unknown"}/${primary.promptId ?? "unknown"}`;
          break;
        case "prompt-delete":
          subject = `prompt(${primary.profileId ?? "unknown"}): delete ${primary.promptCategory ?? "unknown"}/${primary.promptId ?? "unknown"}`;
          break;
        case "reference-doc":
        case "reference-index":
        case "legacy-knowledge-migration":
          subject = `knowledge(${primary.profileId ?? "unknown"}): update ${fileCountLabel}`;
          break;
        case "agent-write-tool":
        case "agent-edit-tool":
          subject = `agent(${primary.profileId ?? "unknown"}): update ${stagedPaths.length === 1 ? "tracked file" : fileCountLabel}`;
          break;
        case "api-write-file":
          subject = uniqueProfiles.length === 1
            ? `knowledge(${uniqueProfiles[0]}): update ${stagedPaths.length === 1 ? "tracked file" : fileCountLabel}`
            : `versioning: update ${fileCountLabel}`;
          break;
        case "api-write-file-restore":
          subject = uniqueProfiles.length === 1
            ? `knowledge(${uniqueProfiles[0]}): restore ${stagedPaths.length === 1 ? "tracked file" : fileCountLabel}`
            : `versioning: restore ${fileCountLabel}`;
          break;
        case "reconcile":
          subject = "versioning: reconcile tracked files";
          break;
        case "bootstrap":
          subject = "versioning: bootstrap tracked files";
          break;
      }
    } else if (reason === "interval") {
      subject = "versioning: reconcile tracked files";
    } else if (uniqueProfiles.length === 1) {
      subject = `versioning(${uniqueProfiles[0]}): update ${fileCountLabel}`;
    }

    const uniqueReviewRunIds = Array.from(
      new Set(mutations.map((mutation) => mutation.reviewRunId?.trim()).filter((value): value is string => Boolean(value)))
    );
    const sharedReviewRunId = uniqueReviewRunIds.length === 1 && mutations.every((mutation) => mutation.reviewRunId?.trim() === uniqueReviewRunIds[0])
      ? uniqueReviewRunIds[0]
      : null;

    const bodyLines = [
      `Reason: ${reason}`,
      uniqueSources.length === 1 ? `Source: ${uniqueSources[0]}` : `Sources: ${uniqueSources.join(", ")}`,
      ...(uniqueProfiles.length === 1 ? [`Profile: ${uniqueProfiles[0]}`] : []),
      ...(primary?.sessionId ? [`Session: ${primary.sessionId}`] : []),
      ...(primary?.agentId ? [`Agent: ${primary.agentId}`] : []),
      ...(sharedReviewRunId ? [`Review-Run: ${sharedReviewRunId}`] : []),
      ...(primary?.promptCategory && primary?.promptId
        ? [`Prompt: ${primary.promptCategory}/${primary.promptId}`]
        : []),
      "Paths:",
      ...stagedPaths.map((path) => `- ${path}`)
    ];

    return {
      subject,
      body: bodyLines.join("\n")
    };
  }

  private async verifyGitAvailability(): Promise<void> {
    const result = await this.git.run(["--version"]);
    const match = /git version (\d+)\.(\d+)/i.exec(result.stdout.trim());
    if (!match) {
      throw new Error(`Unable to parse git version from '${result.stdout.trim()}'`);
    }

    const major = Number.parseInt(match[1], 10);
    const minor = Number.parseInt(match[2], 10);
    if (major < MIN_GIT_MAJOR || (major === MIN_GIT_MAJOR && minor < MIN_GIT_MINOR)) {
      throw new Error(`Git ${MIN_GIT_MAJOR}.${MIN_GIT_MINOR}+ is required for versioning`);
    }
  }

  private async ensureRepositoryInitialized(): Promise<void> {
    const gitDir = join(this.dataDir, ".git");
    try {
      const gitDirStats = await stat(gitDir);
      if (!gitDirStats.isDirectory()) {
        throw new Error(`${gitDir} exists but is not a directory`);
      }
    } catch (error) {
      if (!isEnoentError(error)) {
        throw error;
      }

      await this.git.run(["init", "--quiet"]);
    }

    const topLevel = await this.git.run(["rev-parse", "--show-toplevel"], { allowFailure: true });
    if (topLevel.exitCode !== 0) {
      await this.git.run(["init", "--quiet"]);
    }

    await this.git.run(["config", "user.name", "Forge"]);
    await this.git.run(["config", "user.email", "forge@local"]);
    await this.git.run(["config", "commit.gpgsign", "false"]);
    await this.git.run(["config", "core.autocrlf", "false"]);
    await this.git.run(["config", "core.filemode", "false"]);
    await this.git.run(["config", "core.quotePath", "false"]);
    await this.ensureExcludeFile();
  }

  private async ensureExcludeFile(): Promise<void> {
    const excludePath = join(this.dataDir, ".git", "info", "exclude");
    await mkdir(dirname(excludePath), { recursive: true });

    let existing = "";
    try {
      existing = await readFile(excludePath, "utf8");
    } catch (error) {
      if (!isEnoentError(error)) {
        throw error;
      }
    }

    if (existing === EXCLUDE_FILE_CONTENT) {
      return;
    }

    await writeFile(excludePath, EXCLUDE_FILE_CONTENT, "utf8");
  }

  private async listIndexedTrackedPaths(): Promise<Set<string>> {
    const result = await this.git.run(["ls-files", "-z"]);
    const tracked = new Set<string>();

    for (const entry of result.stdout.split("\0")) {
      const path = entry.trim();
      if (!path) {
        continue;
      }

      if (isTrackedVersionedPath(this.dataDir, join(this.dataDir, path), {
        trackSessionMemory: this.trackSessionMemory
      })) {
        tracked.add(path);
      }
    }

    return tracked;
  }

  private async filterStageablePaths(paths: string[], indexedTrackedPaths: Set<string>): Promise<string[]> {
    const stageable = new Set<string>();

    for (const candidate of paths) {
      const normalized = candidate.replace(/\\/g, "/").trim();
      if (!normalized) {
        continue;
      }

      if (indexedTrackedPaths.has(normalized)) {
        stageable.add(normalized);
        continue;
      }

      try {
        const fileStats = await stat(join(this.dataDir, normalized));
        if (fileStats.isFile()) {
          stageable.add(normalized);
        }
      } catch (error) {
        if (!isEnoentError(error)) {
          throw error;
        }
      }
    }

    return Array.from(stageable).sort((left, right) => left.localeCompare(right));
  }

  private async hasHead(): Promise<boolean> {
    const result = await this.git.run(["rev-parse", "--verify", "HEAD"], { allowFailure: true });
    return result.exitCode === 0;
  }

  private scheduleDebouncedFlush(): void {
    this.clearFlushTimer();
    this.flushTimer = setTimeout(() => {
      void this.flushPending("debounce").catch((error) => {
        this.handleBackgroundFailure("debounce flush", error);
      });
    }, this.debounceMs);
  }

  private clearFlushTimer(): void {
    if (!this.flushTimer) {
      return;
    }
    clearTimeout(this.flushTimer);
    this.flushTimer = undefined;
  }

  private getPendingMutationEntriesSnapshot(): Array<[string, VersioningMutation]> {
    return Array.from(this.pendingMutations.entries());
  }

  private deletePendingMutationEntries(entries: Array<[string, VersioningMutation]>): void {
    for (const [path, mutation] of entries) {
      if (this.pendingMutations.get(path) === mutation) {
        this.pendingMutations.delete(path);
      }
    }
  }

  private async enqueueGitOperation(task: () => Promise<void>): Promise<void> {
    const next = this.gitOperationQueue.then(task, task);
    this.gitOperationQueue = next.then(
      () => undefined,
      () => undefined
    );
    return next;
  }

  private handleBackgroundFailure(operation: string, error: unknown): void {
    const message = stringifyError(error);
    this.logger.warn(`[versioning] ${operation} failed: ${message}`);
    this.disable(message);
  }

  private disable(reason: string): void {
    this.clearFlushTimer();
    if (this.reconcileTimer) {
      clearInterval(this.reconcileTimer);
      this.reconcileTimer = undefined;
    }
    this.enabled = false;
    this.started = false;
    this.logger.warn(`[versioning] Embedded Git versioning disabled: ${reason}`);
  }
}

function parseEnabledEnv(value: string | undefined): boolean {
  const normalized = value?.trim().toLowerCase();
  if (!normalized) {
    return true;
  }

  return !["0", "false", "no", "off"].includes(normalized);
}

function parseTrackSessionMemoryEnv(): boolean {
  const normalized = (process.env.FORGE_VERSIONING_TRACK_SESSION_MEMORY ?? process.env.MIDDLEMAN_VERSIONING_TRACK_SESSION_MEMORY)
    ?.trim()
    .toLowerCase();
  if (!normalized) {
    return false;
  }

  return ["1", "true", "yes", "on"].includes(normalized);
}

function parseReconcileIntervalEnv(): number {
  const raw = (process.env.FORGE_VERSIONING_RECONCILE_INTERVAL_MS ?? process.env.MIDDLEMAN_VERSIONING_RECONCILE_INTERVAL_MS)?.trim();
  if (!raw) {
    return DEFAULT_RECONCILE_INTERVAL_MS;
  }

  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed >= 0 ? parsed : DEFAULT_RECONCILE_INTERVAL_MS;
}

function isEnoentError(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: string }).code === "ENOENT"
  );
}

function stringifyError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
