import type { ForgeModelCatalog } from './model-catalog-types.js'

/**
 * Forge Model Catalog — authoritative source of truth for all supported models.
 *
 * Add or update supported models here. Do not add model metadata in UI fallbacks,
 * ad-hoc route helpers, or provider-specific extensions.
 *
 * Schema: providers → families → models (model-centric first, families are a manager UX projection).
 */
export const FORGE_MODEL_CATALOG = {
  providers: {
    'openai-codex': {
      providerId: 'openai-codex',
      displayName: 'OpenAI Codex',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'built-in-overrides',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
    },
    anthropic: {
      providerId: 'anthropic',
      displayName: 'Anthropic',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'built-in-overrides',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
    },
    'claude-sdk': {
      providerId: 'claude-sdk',
      displayName: 'Claude SDK',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'none',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
    },
    xai: {
      providerId: 'xai',
      displayName: 'xAI',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'custom-provider-merge',
      projectionScope: 'full-upstream-provider',
      requestBehaviorId: 'xai-responses',
      piBaseUrl: 'https://api.x.ai/v1',
      piApiKeyEnvVar: 'XAI_API_KEY',
      piApiProtocol: 'openai-responses',
    },
    openrouter: {
      providerId: 'openrouter',
      displayName: 'OpenRouter',
      availabilityMode: 'external',
      piProjectionMode: 'custom-provider-merge',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
      piBaseUrl: 'https://openrouter.ai/api/v1',
      piApiKeyEnvVar: 'OPENROUTER_API_KEY',
      piApiProtocol: 'openai-completions',
    },
    'cursor-sdk': {
      providerId: 'cursor-sdk',
      displayName: 'Cursor SDK',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'none',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
    },
  },

  families: {
    'pi-codex': {
      familyId: 'pi-codex',
      displayName: 'GPT-5.5 (legacy Codex alias)',
      provider: 'openai-codex',
      defaultModelId: 'gpt-5.5',
      defaultReasoningLevel: 'xhigh',
      visibleInCreateManager: false,
      visibleInChangeManager: false,
      visibleInSpawnPreset: false,
      visibleInSpecialists: false,
    },
    'pi-5.5': {
      familyId: 'pi-5.5',
      displayName: 'GPT-5.5',
      provider: 'openai-codex',
      defaultModelId: 'gpt-5.5',
      defaultReasoningLevel: 'xhigh',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-codex-spark': {
      familyId: 'pi-codex-spark',
      displayName: 'GPT-5.3 Codex Spark',
      provider: 'openai-codex',
      defaultModelId: 'gpt-5.3-codex-spark',
      defaultReasoningLevel: 'low',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-5.4': {
      familyId: 'pi-5.4',
      displayName: 'GPT-5.4',
      provider: 'openai-codex',
      defaultModelId: 'gpt-5.4',
      defaultReasoningLevel: 'xhigh',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-opus': {
      familyId: 'pi-opus',
      displayName: 'Claude Opus 4.8',
      provider: 'anthropic',
      defaultModelId: 'claude-opus-4-8',
      defaultReasoningLevel: 'high',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-sonnet': {
      familyId: 'pi-sonnet',
      displayName: 'Claude Sonnet 5',
      provider: 'anthropic',
      defaultModelId: 'claude-sonnet-5',
      defaultReasoningLevel: 'medium',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'sdk-opus': {
      familyId: 'sdk-opus',
      displayName: 'Claude Opus 4.8 (SDK)',
      provider: 'claude-sdk',
      defaultModelId: 'claude-opus-4-8',
      defaultReasoningLevel: 'high',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'sdk-sonnet': {
      familyId: 'sdk-sonnet',
      displayName: 'Claude Sonnet 5 (SDK)',
      provider: 'claude-sdk',
      defaultModelId: 'claude-sonnet-5',
      defaultReasoningLevel: 'medium',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-grok': {
      familyId: 'pi-grok',
      displayName: 'Grok 4',
      provider: 'xai',
      defaultModelId: 'grok-4',
      defaultReasoningLevel: 'high',
      visibleInCreateManager: false,
      visibleInChangeManager: false,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'cursor-composer': {
      familyId: 'cursor-composer',
      displayName: 'Composer 2.5 (Cursor SDK)',
      provider: 'cursor-sdk',
      defaultModelId: 'composer-2.5',
      defaultReasoningLevel: 'none',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'cursor-grok-45': {
      familyId: 'cursor-grok-45',
      displayName: 'Grok 4.5 (Cursor SDK)',
      provider: 'cursor-sdk',
      defaultModelId: 'grok-4.5',
      defaultReasoningLevel: 'high',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
  },

  models: {
    // ── OpenAI Codex models ────────────────────────────────
    'gpt-5.5': {
      modelId: 'gpt-5.5',
      provider: 'openai-codex',
      familyId: 'pi-5.5',
      displayName: 'GPT-5.5',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'xhigh',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.5',
      intentionalDivergenceNotes: null,
    },
    'gpt-5.3-codex-spark': {
      modelId: 'gpt-5.3-codex-spark',
      provider: 'openai-codex',
      familyId: 'pi-codex-spark',
      displayName: 'GPT-5.3 Codex Spark',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'low',
      contextWindow: 128_000,
      maxOutputTokens: 128_000,
      inputModes: ['text'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.3-codex-spark',
      intentionalDivergenceNotes: null,
    },
    'gpt-5.4': {
      modelId: 'gpt-5.4',
      provider: 'openai-codex',
      familyId: 'pi-5.4',
      displayName: 'GPT-5.4',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'xhigh',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.4',
      intentionalDivergenceNotes: null,
    },
    'gpt-5.4-mini': {
      modelId: 'gpt-5.4-mini',
      provider: 'openai-codex',
      familyId: 'pi-5.4',
      displayName: 'GPT-5.4 Mini',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'high',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.4-mini',
      intentionalDivergenceNotes: null,
    },

    // ── Anthropic models ────────────────────────────────
    'claude-opus-4-8': {
      modelId: 'claude-opus-4-8',
      provider: 'anthropic',
      familyId: 'pi-opus',
      displayName: 'Claude Opus 4.8',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-opus-4-8',
      intentionalDivergenceNotes:
        'Pending Pi upstream; projected via Forge catalog allowlist until Pi ships claude-opus-4-8.',
    },
    'claude-opus-4-7': {
      modelId: 'claude-opus-4-7',
      provider: 'anthropic',
      familyId: 'pi-opus',
      displayName: 'Claude Opus 4.7',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-opus-4-7',
      intentionalDivergenceNotes: null,
    },
    'claude-opus-4-6': {
      modelId: 'claude-opus-4-6',
      provider: 'anthropic',
      familyId: 'pi-opus',
      displayName: 'Claude Opus 4.6',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-opus-4-6',
      intentionalDivergenceNotes: null,
    },
    'claude-sonnet-5': {
      modelId: 'claude-sonnet-5',
      provider: 'anthropic',
      familyId: 'pi-sonnet',
      displayName: 'Claude Sonnet 5',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'medium',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-sonnet-5',
      intentionalDivergenceNotes:
        'Pending Pi upstream; projected via Forge catalog allowlist until Pi ships claude-sonnet-5.',
    },
    'claude-sonnet-4-5-20250929': {
      modelId: 'claude-sonnet-4-5-20250929',
      provider: 'anthropic',
      familyId: 'pi-sonnet',
      displayName: 'Claude Sonnet 4.5',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'medium',
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-sonnet-4-5-20250929',
      intentionalDivergenceNotes: null,
    },
    'claude-haiku-4-5-20251001': {
      modelId: 'claude-haiku-4-5-20251001',
      provider: 'anthropic',
      familyId: 'pi-opus',
      displayName: 'Claude Haiku 4.5',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'low',
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-haiku-4-5-20251001',
      intentionalDivergenceNotes: null,
    },

    // ── Claude SDK models ────────────────────────────────
    'claude-sdk/claude-opus-4-8': {
      catalogId: 'claude-sdk/claude-opus-4-8',
      modelId: 'claude-opus-4-8',
      provider: 'claude-sdk',
      familyId: 'sdk-opus',
      displayName: 'Claude Opus 4.8 (SDK)',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes: 'Synthetic native Claude Agent SDK runtime variant.',
    },
    'claude-sdk/claude-opus-4-7': {
      catalogId: 'claude-sdk/claude-opus-4-7',
      modelId: 'claude-opus-4-7',
      provider: 'claude-sdk',
      familyId: 'sdk-opus',
      displayName: 'Claude Opus 4.7 (SDK)',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes: 'Synthetic native Claude Agent SDK runtime variant.',
    },
    'claude-sdk/claude-opus-4-6': {
      catalogId: 'claude-sdk/claude-opus-4-6',
      modelId: 'claude-opus-4-6',
      provider: 'claude-sdk',
      familyId: 'sdk-opus',
      displayName: 'Claude Opus 4.6 (SDK)',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes: 'Synthetic native Claude Agent SDK runtime variant.',
    },
    'claude-sdk/claude-sonnet-5': {
      catalogId: 'claude-sdk/claude-sonnet-5',
      modelId: 'claude-sonnet-5',
      provider: 'claude-sdk',
      familyId: 'sdk-sonnet',
      displayName: 'Claude Sonnet 5 (SDK)',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'medium',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes: 'Synthetic native Claude Agent SDK runtime variant.',
    },
    'claude-sdk/claude-sonnet-4-5-20250929': {
      catalogId: 'claude-sdk/claude-sonnet-4-5-20250929',
      modelId: 'claude-sonnet-4-5-20250929',
      provider: 'claude-sdk',
      familyId: 'sdk-sonnet',
      displayName: 'Claude Sonnet 4.5 (SDK)',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'medium',
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes: 'Synthetic native Claude Agent SDK runtime variant.',
    },
    'claude-sdk/claude-haiku-4-5-20251001': {
      catalogId: 'claude-sdk/claude-haiku-4-5-20251001',
      modelId: 'claude-haiku-4-5-20251001',
      provider: 'claude-sdk',
      familyId: 'sdk-opus',
      displayName: 'Claude Haiku 4.5 (SDK)',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'low',
      contextWindow: 200_000,
      maxOutputTokens: 64_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes: 'Synthetic native Claude Agent SDK runtime variant.',
    },

    // ── xAI models ────────────────────────────────
    'grok-4': {
      modelId: 'grok-4',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'high',
      contextWindow: 256_000,
      maxOutputTokens: 64_000,
      inputModes: ['text'],
      webSearchCapability: 'native',
      enabledByDefault: true,
      piUpstreamId: 'grok-4',
      intentionalDivergenceNotes:
        "Forge overrides Pi's built-in openai-completions API to openai-responses via xai-responses behavior adapter",
    },
    'grok-4-fast': {
      modelId: 'grok-4-fast',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4 Fast',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'medium',
      contextWindow: 2_000_000,
      maxOutputTokens: 30_000,
      inputModes: ['text'],
      webSearchCapability: 'native',
      enabledByDefault: true,
      piUpstreamId: 'grok-4-fast',
      intentionalDivergenceNotes:
        'API overridden to openai-responses; Forge keeps this model text-only even though Pi upstream currently advertises image input',
    },
    'grok-4.20-0309-reasoning': {
      modelId: 'grok-4.20-0309-reasoning',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4.20 Reasoning',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'high',
      contextWindow: 2_000_000,
      maxOutputTokens: 30_000,
      inputModes: ['text'],
      webSearchCapability: 'native',
      enabledByDefault: true,
      piUpstreamId: 'grok-4.20-0309-reasoning',
      intentionalDivergenceNotes:
        'API overridden to openai-responses; Forge keeps this model text-only even though Pi upstream currently advertises image input',
    },
    'grok-4.20-0309-non-reasoning': {
      modelId: 'grok-4.20-0309-non-reasoning',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4.20 Non-Reasoning',
      isFamilyDefault: false,
      supportsReasoning: false,
      supportedReasoningLevels: ['none'],
      defaultReasoningLevel: 'none',
      contextWindow: 2_000_000,
      maxOutputTokens: 30_000,
      inputModes: ['text'],
      webSearchCapability: 'native',
      enabledByDefault: true,
      piUpstreamId: 'grok-4.20-0309-non-reasoning',
      intentionalDivergenceNotes:
        'API overridden to openai-responses; reasoning: false per Pi upstream; Forge keeps this model text-only even though Pi upstream currently advertises image input',
    },

    'cursor-sdk/composer-2.5': {
      catalogId: 'cursor-sdk/composer-2.5',
      modelId: 'composer-2.5',
      provider: 'cursor-sdk',
      familyId: 'cursor-composer',
      displayName: 'Composer 2.5',
      isFamilyDefault: true,
      supportsReasoning: false,
      supportedReasoningLevels: ['none'],
      defaultReasoningLevel: 'none',
      contextWindow: 200_000,
      maxOutputTokens: 16_384,
      inputModes: ['text'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes:
        'Synthetic entry — Cursor SDK local runtime is not a Pi-managed runtime; curated from live Cursor SDK discovery, which exposed only a fast toggle for Composer 2.5 and no controllable reasoning effort',
    },
    'cursor-sdk/grok-4.5': {
      catalogId: 'cursor-sdk/grok-4.5',
      modelId: 'grok-4.5',
      provider: 'cursor-sdk',
      familyId: 'cursor-grok-45',
      displayName: 'Grok 4.5',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 500_000,
      maxOutputTokens: 64_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes:
        'Synthetic entry — curated from live Cursor SDK discovery: SDK model id is grok-4.5 with effort and fast params; provider-scoped to avoid collision with xAI/Pi Grok ids',
    },
    'cursor-sdk/grok-4.5-fast': {
      catalogId: 'cursor-sdk/grok-4.5-fast',
      modelId: 'grok-4.5-fast',
      provider: 'cursor-sdk',
      familyId: 'cursor-grok-45',
      displayName: 'Grok 4.5 Fast',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 500_000,
      maxOutputTokens: 64_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes:
        'Synthetic entry — represented as a Forge model variant for attribution, but sent to Cursor SDK as model id grok-4.5 with fast=true based on live-discovered params',
    },
  },
} as const satisfies ForgeModelCatalog

const catalogFamilies = FORGE_MODEL_CATALOG.families as Record<string, { familyId: string }>

/** All family IDs, derived from the catalog. Replaces the manual MANAGER_MODEL_PRESETS tuple. */
export const CATALOG_FAMILY_IDS = Object.keys(catalogFamilies) as readonly string[]
