import type { ForgeModelCatalog } from './model-catalog-types.js'

/**
 * Forge Model Catalog — authoritative source of truth for all supported models.
 *
 * Add or update supported models here. Do not add model metadata in UI fallbacks,
 * ad-hoc route helpers, or provider-specific extensions.
 *
 * Schema: providers → families → models (model-centric first, families are a manager UX projection).
 */
export const FORGE_MODEL_CATALOG = {
  providers: {
    'openai-codex': {
      providerId: 'openai-codex',
      displayName: 'OpenAI Codex',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'built-in-overrides',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
    },
    anthropic: {
      providerId: 'anthropic',
      displayName: 'Anthropic',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'built-in-overrides',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
    },
    xai: {
      providerId: 'xai',
      displayName: 'xAI',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'custom-provider-merge',
      projectionScope: 'approved-provider-models',
      requestBehaviorId: 'xai-responses',
      piBaseUrl: 'https://api.x.ai/v1',
      piApiKeyEnvVar: 'XAI_API_KEY',
      piApiProtocol: 'openai-responses',
    },
    openrouter: {
      providerId: 'openrouter',
      displayName: 'OpenRouter',
      availabilityMode: 'external',
      piProjectionMode: 'custom-provider-merge',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
      piBaseUrl: 'https://openrouter.ai/api/v1',
      piApiKeyEnvVar: 'OPENROUTER_API_KEY',
      piApiProtocol: 'openai-completions',
    },
    'cursor-sdk': {
      providerId: 'cursor-sdk',
      displayName: 'Cursor SDK',
      availabilityMode: 'managed-auth',
      piProjectionMode: 'none',
      projectionScope: 'catalog-only',
      requestBehaviorId: null,
    },
  },

  families: {
    'pi-codex': {
      familyId: 'pi-codex',
      displayName: 'GPT-5.5 (legacy Codex alias)',
      provider: 'openai-codex',
      defaultModelId: 'gpt-5.5',
      defaultReasoningLevel: 'xhigh',
      visibleInCreateManager: false,
      visibleInChangeManager: false,
      visibleInSpawnPreset: false,
      visibleInSpecialists: false,
    },
    'pi-5.5': {
      familyId: 'pi-5.5',
      displayName: 'GPT-5.5',
      provider: 'openai-codex',
      defaultModelId: 'gpt-5.5',
      defaultReasoningLevel: 'xhigh',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-5.6': {
      familyId: 'pi-5.6',
      displayName: 'GPT-5.6',
      provider: 'openai-codex',
      defaultModelId: 'gpt-5.6-sol',
      defaultReasoningLevel: 'max',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-5.4': {
      familyId: 'pi-5.4',
      displayName: 'GPT-5.4',
      provider: 'openai-codex',
      defaultModelId: 'gpt-5.4',
      defaultReasoningLevel: 'xhigh',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-opus': {
      familyId: 'pi-opus',
      displayName: 'Claude Opus 5',
      provider: 'anthropic',
      defaultModelId: 'claude-opus-5',
      defaultReasoningLevel: 'high',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-sonnet': {
      familyId: 'pi-sonnet',
      displayName: 'Claude Sonnet 5',
      provider: 'anthropic',
      defaultModelId: 'claude-sonnet-5',
      defaultReasoningLevel: 'medium',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-fable': {
      familyId: 'pi-fable',
      displayName: 'Claude Fable 5',
      provider: 'anthropic',
      defaultModelId: 'claude-fable-5',
      defaultReasoningLevel: 'high',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'pi-grok': {
      familyId: 'pi-grok',
      displayName: 'Grok 4.6',
      provider: 'xai',
      defaultModelId: 'grok-4.6',
      defaultReasoningLevel: 'high',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'cursor-composer': {
      familyId: 'cursor-composer',
      displayName: 'Composer 2.5 (Cursor SDK)',
      provider: 'cursor-sdk',
      defaultModelId: 'composer-2.5',
      defaultReasoningLevel: 'none',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
    'cursor-grok-45': {
      familyId: 'cursor-grok-45',
      displayName: 'Grok 4.5 (Cursor SDK)',
      provider: 'cursor-sdk',
      defaultModelId: 'grok-4.5',
      defaultReasoningLevel: 'high',
      visibleInCreateManager: true,
      visibleInChangeManager: true,
      visibleInSpawnPreset: true,
      visibleInSpecialists: true,
    },
  },

  models: {
    // ── OpenAI Codex models ────────────────────────────────
    'gpt-5.5': {
      modelId: 'gpt-5.5',
      provider: 'openai-codex',
      familyId: 'pi-5.5',
      displayName: 'GPT-5.5',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'xhigh',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.5',
      intentionalDivergenceNotes: null,
    },
    'gpt-5.6-sol': {
      modelId: 'gpt-5.6-sol',
      provider: 'openai-codex',
      familyId: 'pi-5.6',
      displayName: 'GPT-5.6 Sol',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high', 'xhigh', 'max', 'ultra'],
      defaultReasoningLevel: 'max',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.6-sol',
      intentionalDivergenceNotes:
        'Intentional divergence: Forge follows the 272k context window reported by Codex capability metadata instead of the 372k value reported by Pi.',
    },
    'gpt-5.6-terra': {
      modelId: 'gpt-5.6-terra',
      provider: 'openai-codex',
      familyId: 'pi-5.6',
      displayName: 'GPT-5.6 Terra',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high', 'xhigh', 'max', 'ultra'],
      defaultReasoningLevel: 'high',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.6-terra',
      intentionalDivergenceNotes:
        'Intentional divergence: Forge follows the 272k context window reported by Codex capability metadata instead of the 372k value reported by Pi.',
    },
    'gpt-5.6-luna': {
      modelId: 'gpt-5.6-luna',
      provider: 'openai-codex',
      familyId: 'pi-5.6',
      displayName: 'GPT-5.6 Luna',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      defaultReasoningLevel: 'high',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.6-luna',
      intentionalDivergenceNotes:
        'Intentional divergence: Forge follows the 272k context window reported by Codex capability metadata instead of the 372k value reported by Pi.',
    },
    'gpt-5.4': {
      modelId: 'gpt-5.4',
      provider: 'openai-codex',
      familyId: 'pi-5.4',
      displayName: 'GPT-5.4',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'xhigh',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.4',
      intentionalDivergenceNotes: null,
    },
    'gpt-5.4-mini': {
      modelId: 'gpt-5.4-mini',
      provider: 'openai-codex',
      familyId: 'pi-5.4',
      displayName: 'GPT-5.4 Mini',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'high',
      contextWindow: 272_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'gpt-5.4-mini',
      intentionalDivergenceNotes: null,
    },

    // ── Anthropic models ────────────────────────────────
    'claude-opus-5': {
      modelId: 'claude-opus-5',
      provider: 'anthropic',
      familyId: 'pi-opus',
      displayName: 'Claude Opus 5',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      thinkingLevelMap: { low: 'low', medium: 'medium', high: 'high', xhigh: 'xhigh', max: 'max' },
      piCompat: { forceAdaptiveThinking: true, supportsTemperature: false },
      piCost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
      enabledByDefault: true,
      piUpstreamId: 'claude-opus-5',
      intentionalDivergenceNotes:
        'Pending Pi upstream; projected via Forge catalog allowlist until Pi ships claude-opus-5.',
    },
    'claude-opus-4-8': {
      modelId: 'claude-opus-4-8',
      provider: 'anthropic',
      familyId: 'pi-opus',
      displayName: 'Claude Opus 4.8',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-opus-4-8',
      intentionalDivergenceNotes:
        'Intentional divergence: Claude Opus 4.8 is restricted to low, medium, and high reasoning levels.',
    },
    'claude-opus-4-7': {
      modelId: 'claude-opus-4-7',
      provider: 'anthropic',
      familyId: 'pi-opus',
      displayName: 'Claude Opus 4.7',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-opus-4-7',
      intentionalDivergenceNotes: null,
    },
    'claude-opus-4-6': {
      modelId: 'claude-opus-4-6',
      provider: 'anthropic',
      familyId: 'pi-opus',
      displayName: 'Claude Opus 4.6',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-opus-4-6',
      intentionalDivergenceNotes: null,
    },
    'claude-sonnet-5': {
      modelId: 'claude-sonnet-5',
      provider: 'anthropic',
      familyId: 'pi-sonnet',
      displayName: 'Claude Sonnet 5',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'medium',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: 'claude-sonnet-5',
      intentionalDivergenceNotes:
        'Pending Pi upstream; projected via Forge catalog allowlist until Pi ships claude-sonnet-5.',
    },
    'claude-fable-5': {
      modelId: 'claude-fable-5',
      provider: 'anthropic',
      familyId: 'pi-fable',
      displayName: 'Claude Fable 5',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
      defaultReasoningLevel: 'high',
      contextWindow: 1_000_000,
      maxOutputTokens: 128_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      thinkingLevelMap: { off: null, xhigh: 'xhigh', max: 'max' },
      enabledByDefault: true,
      piUpstreamId: 'claude-fable-5',
      intentionalDivergenceNotes: null,
    },
    // ── xAI models ────────────────────────────────
    'grok-4.6': {
      modelId: 'grok-4.6',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4.6',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'high',
      contextWindow: 500_000,
      maxOutputTokens: 500_000,
      inputModes: ['text', 'image'],
      outputModes: ['text'],
      supportsTools: true,
      supportsStructuredOutput: true,
      authScope: 'any',
      webSearchCapability: 'native',
      thinkingLevelMap: { off: null, low: 'low', medium: 'medium', high: 'high', xhigh: 'xhigh' },
      piCost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 },
      enabledByDefault: true,
      piUpstreamId: 'grok-4.6',
      intentionalDivergenceNotes:
        'Pending Pi upstream; projected from xAI Grok 4.6 provider metadata until Pi ships grok-4.6. Forge uses the 500k context limit as Pi\'s required numeric max-output bound because xAI documents no separate text output limit.',
    },
    'grok-4.5': {
      modelId: 'grok-4.5',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4.5',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'high',
      contextWindow: 500_000,
      maxOutputTokens: 500_000,
      inputModes: ['text', 'image'],
      outputModes: ['text'],
      supportsTools: true,
      supportsStructuredOutput: true,
      authScope: 'any',
      webSearchCapability: 'native',
      thinkingLevelMap: { off: null, low: 'low', medium: 'medium', high: 'high', xhigh: 'xhigh' },
      enabledByDefault: true,
      piUpstreamId: 'grok-4.5',
      intentionalDivergenceNotes:
        'Canonical native xAI row. OAuth discovery may narrow or extend reasoning metadata for the authenticated account.',
    },
    'grok-4': {
      modelId: 'grok-4',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'high',
      contextWindow: 256_000,
      maxOutputTokens: 64_000,
      inputModes: ['text'],
      webSearchCapability: 'native',
      enabledByDefault: true,
      piUpstreamId: 'grok-4',
      intentionalDivergenceNotes:
        'Pi 0.80.6 removed grok-4 from the upstream xAI catalog. Forge retains this curated row and continues routing it through the openai-responses xAI behavior adapter.',
    },
    'grok-4-fast': {
      modelId: 'grok-4-fast',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4 Fast',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'medium',
      contextWindow: 2_000_000,
      maxOutputTokens: 30_000,
      inputModes: ['text'],
      webSearchCapability: 'native',
      enabledByDefault: true,
      piUpstreamId: 'grok-4-fast',
      intentionalDivergenceNotes:
        'Pi 0.80.6 removed grok-4-fast from the upstream xAI catalog. Forge retains this curated text-only row and routes it through the openai-responses xAI behavior adapter.',
    },
    'grok-4.20-0309-reasoning': {
      modelId: 'grok-4.20-0309-reasoning',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4.20 Reasoning',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['none', 'low', 'medium', 'high', 'xhigh'],
      defaultReasoningLevel: 'high',
      contextWindow: 2_000_000,
      maxOutputTokens: 30_000,
      inputModes: ['text'],
      webSearchCapability: 'native',
      enabledByDefault: true,
      piUpstreamId: 'grok-4.20-0309-reasoning',
      intentionalDivergenceNotes:
        'API overridden to openai-responses; Forge keeps this model text-only even though Pi upstream currently advertises image input',
    },
    'grok-4.20-0309-non-reasoning': {
      modelId: 'grok-4.20-0309-non-reasoning',
      provider: 'xai',
      familyId: 'pi-grok',
      displayName: 'Grok 4.20 Non-Reasoning',
      isFamilyDefault: false,
      supportsReasoning: false,
      supportedReasoningLevels: ['none'],
      defaultReasoningLevel: 'none',
      contextWindow: 2_000_000,
      maxOutputTokens: 30_000,
      inputModes: ['text'],
      webSearchCapability: 'native',
      enabledByDefault: true,
      piUpstreamId: 'grok-4.20-0309-non-reasoning',
      intentionalDivergenceNotes:
        'API overridden to openai-responses; reasoning: false per Pi upstream; Forge keeps this model text-only even though Pi upstream currently advertises image input',
    },

    'cursor-sdk/composer-2.5': {
      catalogId: 'cursor-sdk/composer-2.5',
      modelId: 'composer-2.5',
      provider: 'cursor-sdk',
      familyId: 'cursor-composer',
      displayName: 'Composer 2.5',
      isFamilyDefault: true,
      supportsReasoning: false,
      supportedReasoningLevels: ['none'],
      defaultReasoningLevel: 'none',
      contextWindow: 200_000,
      maxOutputTokens: 16_384,
      inputModes: ['text'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes:
        'Synthetic entry — Cursor SDK local runtime is not a Pi-managed runtime; curated from live Cursor SDK discovery, which exposed only a fast toggle for Composer 2.5 and no controllable reasoning effort',
    },
    'cursor-sdk/grok-4.5': {
      catalogId: 'cursor-sdk/grok-4.5',
      modelId: 'grok-4.5',
      provider: 'cursor-sdk',
      familyId: 'cursor-grok-45',
      displayName: 'Grok 4.5',
      isFamilyDefault: true,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 500_000,
      maxOutputTokens: 64_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes:
        'Synthetic entry — curated from live Cursor SDK discovery: SDK model id is grok-4.5 with effort and fast params; provider-scoped to avoid collision with xAI/Pi Grok ids',
    },
    'cursor-sdk/grok-4.5-fast': {
      catalogId: 'cursor-sdk/grok-4.5-fast',
      modelId: 'grok-4.5-fast',
      provider: 'cursor-sdk',
      familyId: 'cursor-grok-45',
      displayName: 'Grok 4.5 Fast',
      isFamilyDefault: false,
      supportsReasoning: true,
      supportedReasoningLevels: ['low', 'medium', 'high'],
      defaultReasoningLevel: 'high',
      contextWindow: 500_000,
      maxOutputTokens: 64_000,
      inputModes: ['text', 'image'],
      webSearchCapability: 'none',
      enabledByDefault: true,
      piUpstreamId: null,
      intentionalDivergenceNotes:
        'Synthetic entry — represented as a Forge model variant for attribution, but sent to Cursor SDK as model id grok-4.5 with fast=true based on live-discovered params',
    },
  },
} as const satisfies ForgeModelCatalog

const catalogFamilies = FORGE_MODEL_CATALOG.families as Record<string, { familyId: string }>

/** All family IDs, derived from the catalog. Replaces the manual MANAGER_MODEL_PRESETS tuple. */
export const CATALOG_FAMILY_IDS = Object.keys(catalogFamilies) as readonly string[]
